import React from 'react';
import { useNavigate } from 'react-router-dom';
import { useEffect } from 'react';
import styles from './css/information.module.css';

import BubblesBackground from './bubblesBackground.js';
import Footer from './footer.js';

const Information = () => {

  // Setting variable for animating the page in/out
  const [animate,setAnimate] = React.useState(false);

  // Setting the scroll animation variables for each section
  const [scrollAnimateDesc,setScrollAnimateDesc] = React.useState(false);
  const [scrollAnimateAuthor,setScrollAnimateAuthor] = React.useState(false);
  const [scrollAnimateFeatures,setScrollAnimateFeatures] = React.useState(false);
  const [scrollAnimateImprovements,setScrollAnimateImprovements] = React.useState(false);

  const navigate = useNavigate();

  // Function to trigger the animation of fading out and navigate to the homepage
  const triggerAnimation = () => {
    setAnimate(true);

    setTimeout(() => navigate("/gcse-maths-quiz-website"), 750);
  }

  // Trigger the animation for sections to fade in as the user scrolls
  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 0) {
        setScrollAnimateDesc(true);
      }
      if (window.scrollY > 600) {
        setScrollAnimateAuthor(true);
      }
      if (window.scrollY > 1000) {
        setScrollAnimateFeatures(true);
      }
      if (window.scrollY > 1500) {
        setScrollAnimateImprovements(true);
      }
    };

    // Add scroll event listener
    window.addEventListener('scroll', handleScroll);

    // Clean up the event listener when component unmounts
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  return (
    <div className={styles.background}>
      <BubblesBackground green={true} animate={animate}/>
      <h1 className={styles.webpageTitle + " " + (animate ? styles.fadeoutContainer: "")}>
        Pace Maths Information
      </h1>
      <span className={styles.homepageButton + " " + (animate ? styles.fadeoutContainer: "")} onClick={triggerAnimation}>
        Return to Homepage
      </span>
      <span className={styles.downArrow}><span class="material-symbols-outlined">arrow_downward</span></span>
      <div className={styles.informationContainer + " " + (animate ? styles.fadeoutContainer: "")}>
        <div className={styles.infoSectionBox}>
          <h1 className={(scrollAnimateDesc ? styles.animateSectionContents : "")}>Website Information</h1>
          <p className={(scrollAnimateDesc ? styles.animateSectionContents : "")}>
            Pace Maths is a website designed for the purpose of aiding in sharpening your maths skills across a variety of topics.
            This is done through the use of quizzes that allow for continuous practice with infinite generated by the website for
            learning purposes. It is designed to be interactive and engaging, allowing for a more enjoyable experience while learning.
          </p>
        </div>
        <div className={styles.sectionBox}>
          <h1 className={(scrollAnimateAuthor ? styles.animateSectionContents : "")}>Author Information</h1>
          <p className={(scrollAnimateAuthor ? styles.animateSectionContents : "")}>
            This website was created by Dawid Paluch, computer science student at Queen Mary University of London. The website is
            also planned to be improved and expanded upon in the future, potentially including contributions from other developers
            that will aid the development of the website.
          </p>
        </div>
        <div className={styles.sectionBox}>
          <h1 className={(scrollAnimateFeatures ? styles.animateSectionContents : "")}>Existing Features</h1>
          <p className={(scrollAnimateFeatures ? styles.animateSectionContents : "")}>
            This website currently only has quizzes to practice ratio, probability, factorisation questions. The questions are very
            limited currently, only being in four formats for ratios and one format each for the other quizzes. The same style of
            problem solving and randomly generated numbers is used for each question format.
          </p>
        </div>
        <div className={styles.sectionBox}>
          <h1  className={(scrollAnimateImprovements ? styles.animateSectionContents : "")}>Future Improvements</h1>
          <p className={(scrollAnimateImprovements ? styles.animateSectionContents : "")}>
            The website is planned to be improved in the future with the addition of more quizzes and question types. This will allow
            for a wider range of topics to be covered and for a more comprehensive learning experience.
          </p>
        </div>
      </div>
      <span className={styles.homepageButton + " " + styles.bottomHomepageButton + " " + (animate ? styles.fadeoutContainer: "")} onClick={triggerAnimation}>
        Return to Homepage
      </span>
      <Footer />
    </div>
  );
}
  
  export default Information;